### ISSUE TITLE
Add 'pending data' options for screening status

### ISSUE THREAD

**Issue by rj-morgan** [publichealthengland/canql#62] opened 2021-02-05 18:40 UTC
As a person using CANQL,

I need ‘pending data’ added to the screening status syntax column,

So that cases that have this screening status can be easily identified without relying on cleaning lists generated in the analysis server. Other screening statuses can be queried for but ‘pending data’ is missing from the syntax.

It is done when:
-    Screening status on diagnosed anomaly = 17 (‘pending data’) is added to the CANQL syntax for screening status column.
-    This applies to cases and patients.

**Comment by drewthorp** [comment] 2021-03-12 13:24
This was a duplicate of a now resolved issue

**Closed** 2021-03-12 13:23 UTC
